{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-deployment-blue
  labels:
    app: crud-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: crud-app
      slot: blue
  template:
    metadata:
      labels:
        app: crud-app
        slot: blue
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: crud-app-blue
          image: '{{ .Values.image }}:{{ .Values.blue.appVersion }}'
          env:
            - name: APP_COLOR
              value: blue
            - name: APP_VERSION
              value: '{{ .Values.blue.appVersion }}'
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgresql:5432/quarkus_test
            - name: QUARKUS_DATASOURCE_USERNAME
              value: quarkus_test
              valueFrom:
              secretKeyRef:
                name: postgresql
                key:  database-user
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: quarkus_test
              valueFrom:
              secretKeyRef:
                name: postgresql
                key:  database-password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            # failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            # failureThreshold: 20
          resources:
            requests:
              memory: {{ .Values.resourcesRequestsMemory }}
              cpu: {{ .Values.resourcesRequestsCpu }}
            limits:
              memory: {{ .Values.resourcesLimitsMemory }}
              cpu: {{ .Values.resourcesLimitsCpu }}
{{ end }}