apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-deployment
  labels:
    app: crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app
          image: nginxinc/nginx-unprivileged 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              memory: '100Mi'
              cpu: '1000m'
            limits:
              memory: "200Mi"
              cpu: "2000m"