image: ghcr.io/joschne-assessment/crud-app
green:
  appVersion: 9bf2384
  enabled: false
blue:
  appVersion: 9bf2384
  enabled: true
productionSlot: blue
replicas: 2
resourcesRequestsMemory: 500Mi
resourcesRequestsCpu: 500m
resourcesLimitsMemory: 500Mi
resourcesLimitsCpu: 500m

