image: ghcr.io/joschne-assessment/crud-app
green:
  appVersion: ba815f6
  enabled: false
blue:
  appVersion: "c42c10b"
  enabled: true
productionSlot: blue
replicas: 2
resourcesRequestsMemory: 500Mi
resourcesRequestsCpu: 500m
resourcesLimitsMemory: 500Mi
resourcesLimitsCpu: 500m
