green:
  appVersion: 1.4
  enabled: true
blue:
  appVersion: 1
  enabled: true
productionSlot: blue
replicas: 4
resourcesRequestsMemory: 100Mi
resourcesRequestsCpu: 100m
resourcesLimitsMemory: 100Mi
resourcesLimitsCpu: 100m
$newSlot:
  appVersion: f178ee0
