image: ghcr.io/joschne-assessment/crud-app
green:
  appVersion: ba815f6
  enabled: false
blue:
  appVersion: "c42c10b"
  enabled: true
productionSlot: blue
replicas: 3
resourcesRequestsMemory: 500Mi
resourcesRequestsCpu: 400m
resourcesLimitsMemory: 500Mi
resourcesLimitsCpu: 400m
