image: ghcr.io/joschne-assessment/crud-app
green:
  appVersion: 48e4dbc
  enabled: true
blue:
  appVersion: "c42c10b"
  enabled: false
productionSlot: green
replicas: 3
resourcesRequestsMemory: 500Mi
resourcesRequestsCpu: 400m
resourcesLimitsMemory: 500Mi
resourcesLimitsCpu: 400m
