# 💁 This workflow will:
# - Checkout the repository
# - Log in to the OpenShift cluster
# - Auto-deploy the given application version using a blue-green strategy 

name: Deploy crud app

env:
  # 🖊️ EDIT your repository secrets to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  # Set the kube context's namespace after login.
  OPENSHIFT_NAMESPACE: "joschne-dev"

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Application version'
        required: true

jobs:
  deploy-crud-app:
    name: Deploy crud app to OpenShift
    runs-on: ubuntu-latest
    permissions: 
      repository-projects: write
    steps:
      - name: Check for required secrets
        uses: actions/github-script@v6
        with:
          script: |
            const secrets = {
              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
            };
  
            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
              if (value.length === 0) {
                core.error(`Secret "${name}" is not set`);
                return true;
              }
              core.info(`✔️ Secret "${name}" is set`);
              return false;
            });
  
            if (missingSecrets.length > 0) {
              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
                "You can add it using:\n" +
                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
            }
            else {
              core.info(`✅ All the required secrets are set`);
            }
  
      - name: Check out repository
        uses: actions/checkout@v4
  
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
  
      # https://github.com/redhat-actions/oc-login#readme
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
  
      - name: Set Git Identity
        run: |
          git config --global user.name 'joschne'
          git config --global user.email 'jonas.schneider@balcab.ch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       

      - name: Deploy Application
        run: |
          git config --global user.name 'joschne'
          git config --global user.email 'jonas.schneider@balcab.ch'
          cd crud-app-chart
          bash _autoDeployBlueOrGreen.sh --app-version ${{ github.event.inputs.app_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       